### ISSUE TITLE
Exclude loopback and private addresses from being proxified

### ISSUE THREAD

**Issue by ValdikSS** [basil00/reqrypt#11]
ReQrypt tries to proxify even local and loopback addresses (it skips only 127.0.0.1, but there's whole 127.0.0.0/8), which is not convenient.

**Comment by basil00** [comment]
Actually this is not a problem since `packet_filter.c` implements a more strict filter anyway.  Nevertheless, I might upgrade the capture filter when/if WinDivert 1.4 is ready.

**Comment by ValdikSS** [comment]
You're correct, sorry.
