### ISSUE TITLE
Any chance to support useful in china, iran?

### ISSUE THREAD

**Issue by jasonliul** [basil00/reqrypt#15]
If reqrypt could force all trafic use ssl, like stunnel does, it will do the trick.
We will expect your "Eureka" moment.
:)

**Comment by basil00** [comment]
ReQrypt is a specific kind of technology (one way tunneling), and this technology is (mostly) not effective against "strong" filtering systems that inspect inbound traffic such as those deployed in China and Iran.  In most other places, inspecting inbound traffic is at the ISP-level uncommon for a few different reasons, namely: costs of tracking TCP state, web response traffic is high volume, no URLs in web response traffic, and dumb IP-based approaches tend to massively overblock.  But in places like China and Iran they are willing to pay the price.

That said, I have heard some anecdotal reports that ReQrypt does work against *some* ISPs in China.

Iran does some additional tricks.  In addition to censoring HTTP, they reportedly rate limit non-HTTP traffic to frustrate circumvention tools.  Projects like [BarbaTunnel](https://github.com/BarbaTunnelCoder/BarbaTunnel/) tunnel traffic over HTTP to get full speeds.

To force all traffic via a 2-way tunnel, this would be a different project to ReQrypt.  It is more like what [Tallow](https://github.com/basil00/TorWall) does, which is a tool that forces all traffic via the Tor network.  Tallow could probably be adapted to other kinds of tunneling, especially for anything supporting SOCKs5.

**Comment by jasonliul** [comment]
@basil00
Thanks for yr valueable info.
