### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by surereddy** [basil00/reqrypt#17]
Hello sir how can please give me how to use example

**Comment by basil00** [comment]
How to use:
 
1. Download and install the latest version: https://github.com/basil00/reqrypt/releases
2. Double-click the ReQrypt desktop icon.
3. Using the ReQrypt web UI, select which "*Hiding Mode*" you want.  The *Passive* mode is the weakest, and the *Active Highest* is the strongest (tunnels all outbound packets).

ReQrypt should now be working.  Under the LOG tab you should be able to see packets being diverted.

If it still does not work:
1. Try disabling IPv6.
2. Try a direct Internet connection bypassing your router.

**Comment by surereddy** [comment]
hello sir how to use on server without GUI .I have server and client without desktop so i need to run on  cli .Can you kindly help me

**Comment by basil00** [comment]
For this, I'd recommend first setting up ReQrypt on a machine with a GUI, then copy the `reqrypt.cache`/`reqrypt.config` files to the machine without the GUI.  Next run ReQrypt with the option `--no-ui`.
