### ISSUE TITLE
reqrypt seems broken after upgrading to v 1.4

### ISSUE THREAD

**Issue by Petru44io** [basil00/reqrypt#23]
Hi, and sorry for my poor english and lack of knowledge - i'm no coder, but an engineer. I live in Ukraine, and reqrypt 1.3. was a perfect solution against blocking measures that use our ISP-s, but when i downloaded and installed new version (1.4) it just stopped doing whatever magick it did. When i launch it, a tray icon appears for a few seconds, then disappears, taking down UI. Tried to install previous version - same thing. Only v.1.1 remains in tray, but urls are blocked whatever settings i change. I've even tried to reinstall OS (Win7 x64) and install v.1.3 - still nothing. Really looking forward for an advice or kinda..

**Comment by basil00** [comment]
Thanks for the report.  First, try running ReQrypt from a `cmd` console.  You should be able to find the executable in the directory `c:\program files (x86)\ReQrypt`, then run `reqrypt.exe`.  If something goes wrong, it should print an error message to the console.  Just copy-and-paste the error here and we can see what the problem is.

**Comment by Petru44io** [comment]
http://funkyimg.com/i/2F5no.png if i got it right..

**Comment by basil00** [comment]
OK, I think the "result too large" bit is not the real error.  The real error should be the text that follows, but I cannot understand it.  Is it possible to copy-and-paste it here?  Then I can probably track it down.

**Comment by basil00** [comment]
I also forgot to mention that you need to run `cmd` with *Administrator Privileges*.

**Comment by WPMGPRoSToTeMa** [comment]
I was getting similar problem until I restarted my PC. Looks like WinDivert was unable to update itself in the system.

**Comment by Petru44io** [comment]
Thanks for your patience. I've decoded those symbols - they say "не удается проверить производителя подписи данного файла. при последнем изменении оборудования или программного обеспечения могла быть произведена остановка неправильно подписанного или поврежденного файла либо вредоносной программы". As far as i know, You do speak russian, otherwise i'll try to translate that message. Also, i'd like to say, that i'm not using any anti-viral soft right now, and the OS is clean and freshly installed. firewall is disabled also.

**Comment by Petru44io** [comment]
Sorry, guys, for taking your time, i've solved the problem. It was all about digital signatures - after disabling it, reqrypt 1.4 works and i'm happy.

**Comment by basil00** [comment]
Thanks for the report anyway.  The newer versions of WinDivert use the SHA256 algorithm for driver signing (as required by Windows 10), but this seems to cause problems for some Windows 7 users.  (In theory it should work fine provided Windows 7 is up-to-date).  It is likely similar to this issue for Tallow (https://github.com/basil00/TorWall/issues/9), so one solution seems to work for Tallow users was to swap the WinDivert drivers for the alternative variant, which can be downloaded here: https://github.com/basil00/Divert/releases

For reference, ReQrypt already uses the "A" variant, so if you have trouble then perhaps the "B" variant will work.  You'll need to extract the `WinDivert32.sys` and `WinDivert64.sys` files from the `WinDivert-1.4.1-B-MINGW.zip` archive, and replace the same files in the `C:\Program Files (x86)\ReQrypt` directory.  Then you'll need to reboot, and perhaps the problem will be fixed.

**Comment by Petru44io** [comment]
And again thank You - best solution in my case, as i just figured out, was installing Microsoft Security Advisory 3033929 update. My regards.
