### ISSUE TITLE
google.com doesn't work

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [basil00/reqrypt#25]
google.ru, google.kz, etc. still work.

**Comment by WPMGPRoSToTeMa** [comment]
Hmmm, now google.com works.

**Comment by WPMGPRoSToTeMa** [comment]
Hmmm, now google.com works, looks like temporarily problems.

**Comment by basil00** [comment]
Could still be a bug, or perhaps just a network issue.  Which version of ReQrypt are you using?

**Comment by WPMGPRoSToTeMa** [comment]
@basil00 the latest one, 1.4.0. But DNS hiding is disabled.
