### ISSUE TITLE
not useful in china

### ISSUE THREAD

**Issue by hoochanlon** [basil00/reqrypt#27]

**Comment by hoochanlon** [comment]
[#15](https://github.com/basil00/reqrypt/issues/15)

**Comment by basil00** [comment]
Yes, see #15.  ReQrypt was never designed to circumvent "strict" ISP-level filters that actively monitor both inbound and outbound traffic.  ReQrypt is mainly intended for more lightweight URL-blacklist based filtering that is common in many countries (including some western countries like the UK).  In these places they also do not wish to degrade Internet performance, so heavyweight two-way filtering is generally a no-no.

For China/Iran users it is recommended to find a stronger circumvention technology based on two-way tunneling, and something that also protects anonymity.

**Comment by hoochanlon** [comment]
tks
