### ISSUE TITLE
Split option. Some sites do not response.

### ISSUE THREAD

**Issue by odkrys** [basil00/reqrypt#34]
I ran reqrypt with --no-iptables --no-ui options.
iptables
```
iptables -I FORWARD -p tcp -m tcp -m mark ! --mark 40402 -j NFQUEUE --dport 443 --queue-num 40403
iptables -I FORWARD -p tcp -m tcp -m mark ! --mark 40402 -j NFQUEUE --dport 80 --queue-num 40403
```
```
Chain FORWARD (policy DROP 0 packets, 0 bytes)
pkts bytes target     prot opt in     out     source               destination
  997 87186 NFQUEUE    tcp  --  any    any     anywhere             anywhere             tcp dpt:www mark match ! 0x9dd2 NFQUEUE num 40403
 5706 1029K NFQUEUE    tcp  --  any    any     anywhere             anywhere             tcp dpt:https mark match ! 0x9dd2 NFQUEUE num 40403
```
Normally it worked but some sites did not respond.
Browser showed ERR_EMPTY_RESPONSE or ERR_SPDY_PROTOCOL_ERROR page.
Their sites worked on windows version.

I tried various options in reqrypt.config.
Is https fragment feature implement badly on linux ?
Any idea?

**Comment by basil00** [comment]
I don't think the split option works anymore, see #26.  It used to work in 2010-2011 when first designed, but does not work with modern CDNs.  It should probably be removed from the UI.
