### ISSUE TITLE
Спасибо огромное за ReQrypt / Thank you so much for ReQrypt

### ISSUE THREAD

**Issue by snookilow** [basil00/reqrypt#36]
RUS: Спасибо огромное за ReQrypt, это просто идеальное оружие против РКН. Сделайте пожалуйста там больше функционала для гибридного трафика с мешаниной DNS Ipv4 и по больше про ipv6 поддержку перекрёстного трафика.

ENG: Thank you so much for ReQrypt, this is just the perfect weapon against RKN. Please do more functionality for hybrid traffic with Ipv4 DNS hash and more on ipv6 support for cross traffic.

**Comment by basil00** [comment]
Thanks.  Things like IPv6 support are needed (already on the TODO list), but there is little time to develop ReQrypt anymore, so I cannot say when it would be added.
