### ISSUE TITLE
How to create the own ReQrypt server?

### ISSUE THREAD

**Issue by Yuanyiis** [basil00/reqrypt#37]
Hi
i want create a own reqrypt server.
but i only find the client.

thank you very much

**Comment by Yuanyiis** [comment]
i know how to create now.
thank you 
please do not reply this issues

**Comment by basil00** [comment]
No problem, but I'll reply anyway in case anyone else is having trouble setting up a server.

* The server (`reqryptd`) can be downloaded [here](https://github.com/basil00/reqrypt/releases), e.g., `reqryptd_X.Y.Z_amd64.deb`.  Alternatively you can try building it from source if you like.
* Make sure you have a VPS/machine that supports spoofing, see [here](https://github.com/basil00/reqrypt/issues/7).

If you get the server working, consider making the URL public so others can use.

**Comment by Doimatcuabautroi** [comment]
Hix, I don't know how to create, plz help me guys ...

**Comment by basil00** [comment]
I've added a quick guide here: #38.
