### ISSUE TITLE
how to tunnel other Port ?e.g SSH tcp port 22

### ISSUE THREAD

**Issue by Yuanyiis** [basil00/reqrypt#41]
Hi
How to add other port number ,e.g TCP PORT 22
and can i tunnle icmp?
i use own reqryptd server for test.
i try to add iptables rule,but it's not work.

thank you very much

**Comment by basil00** [comment]
See the basic guide in #38.

ReQrypt does not currently support TCP for tunneling.

For icmp, use the `ping` protocol:

    reqryptd --add ping://HOST:PORT?crypt=STRING,sec.2888

Note if you want to use this mode then you should also disable ping:

     echo  1  > /proc/sys/net/ipv4/icmp_echo_ignore_all

**Comment by Yuanyiis** [comment]
sorry,maybe i said wrong,i don't want change the reqryptd port.
i mean else tcp 80/443 udp/53 port.
the default only support 80/443 and udp 53 tunnelling.
can i support tunnelling other tcp ports?like tcp 22 tcp 8080...

**Comment by basil00** [comment]
Sorry I misunderstood.  Currently ReQrypt only supports tcp 80/443 and udp 53.  The only way to change this would be to customize the source code.
