### ISSUE TITLE
Does something wrong with then default servers or my isp blocked reqrypt?

### ISSUE THREAD

**Issue by Razor221** [basil00/reqrypt#43]
Hello,

Up until  today everthing was working flawlessly. However today reqrypt wasnt working.
Eventhough, in the configuration page starts with localhost servers look green.
Like in this picture;

https://prntscr.com/oosji3

Also, while using reqrypt no website open up and i get this message for blocked sites.

https://prntscr.com/oosjet

For non bloked sites i get a message like this

https://prnt.sc/ooy8n6

I use google's dns but to be make sure about it i also used dnscrypt and used cloudflare's dns wıth DoH bu the result was the same. Also checked firewall and reqrypt isn't blocked. 

My question is does my isp bloked the default servers or is there a problem with the default servers?

**Comment by Razor221** [comment]
I have found what was the problem. My ISP changed their ip assignment to what's called as cgnat(carrier grade nat or something) so i was sharing my public ip address with other users on the network and that probably messed up the reqrypt. Today, i called my ISP and told them to give me a dedicated ip address and now everything works. If your assigned ip address in the modem's configuration page is a private ip address. 

Reqrypt will not work and you should contact your ISP for them to you give a real ip address.

These are the private ip number ranges 10.0.0.0 – 10.255.255.255, 172.16.0.0 – 172.31.255.255,100.64.0.0–100.127.255.255,192.168.0.0–192.168.255.255 or 198.18.0.0–198.19.255.255

Question to basil00 is there any way to circumvent the cgnat with reqrypt? 

I was lucky that my ISP still offers real ip addresses but there are some other ISP's that don't even offer or use real ip addresses for their customers anymore in my country. They just use cgnat.

**Comment by basil00** [comment]
> Question to basil00 is there any way to circumvent the cgnat with reqrypt?

You can try increasing the *Ghost Packet Hops* setting to higher values (e.g., 4, 5, 6). The "ghost" packets need to reach the NAT but not the destination website.  It may or may not work, depending on the NAT implementation.

**Comment by quyirah** [comment]
@Razor221 
Hey, another Turkish user here. Are you using Kablonet by any chance? Suddenly this error started to pop-up when I run ReQrypt. I don't know if I should ask for dedicated IP address. I was using ReQrypt without any error since a year.
