### ISSUE TITLE
I can't load anything with ReQrypt anymore

### ISSUE THREAD

**Issue by quyirah** [basil00/reqrypt#45]
I was using ReQrypt since a year without any problems but it doesn't work for me anymore. This started yesterday and I can't load anything with ReQrypt anymore. I haven't done anything related with my PC settings. It started from nowhere and when I open ReQrypt as normal, I am getting this error on Vivaldi when I try to load any normal page like Twitter: ERR_CONNECTION_RESET

When I close program back, I can load every page(not blocked ones) without any problem.

**Comment by quyirah** [comment]
Sorry, I searched first and thought this issue-owner's from different country but it seems like there's a problem with Turkish ISP's. 
https://github.com/basil00/reqrypt/issues/43

**Comment by Razor221** [comment]
It's about the CGNAT that is used by Turkish ISPs. I'm get my internet service from Millenicom in Turkey like you and if i'm in the cgnat pool reqrypt doesnt work even if i use nat traversal from the reqrypt settings. Contact you isp and tell them to remove you from the cgnat pool and tell them to give you a real ip address. I called millenicom and they removed me from cgnat pool and after i got a real ip address reqrypt started to work again.

**Comment by quyirah** [comment]
Need help from @basil00 here. 
Is there any way to fix this issue without asking for dedicated IP address?

@Razor221 (Turkish)
Hocam IP adresim CGN havuzunda mı nasıl anlayabilirim? 92.54 ile başlıyor. Kablonet'in müşteri hizmetleriyle uğraşmayı hiç istemiyorum şu saatte

**Comment by Razor221** [comment]
Modeminin ayar sayfasına gir ve ayar sayfasındaki aldığın ip adresine bak. Eğer modemdeki ip adresi 10.0.0.0 – 10.255.255.255, 172.16.0.0 – 172.31.255.255,100.64.0.0–100.127.255.255,192.168.0.0–192.168.255.255 or 198.18.0.0–198.19.255.255 bunlardan herhangi bir ile başlıyorsa CGNAT havuzundasın demektir.

**Comment by quyirah** [comment]
94 ile başlıyor bu listede değilim. DH'de gördüğüm kadarıyla modem sayfasında yer alan IP adresiyle herhangi bir IP adresi sorgulama sitesine girdiğimde aynı IP'yi görüyorsam CGNAT havuzunda olmuyormuşum. Modem sayfasında da, whatsmyip'de de 94 ile başlayan aynı adresi görüyorum. Yani sorunum CGNAT'lık değil galiba.

**Comment by Razor221** [comment]
Reqrypt açıkken yasaklı olmayan siteler açılıyormu?
Sorun kablonet'in DNS filtering yapmasıda olabilir. Simple DnsCrypt ile dns adresini cloudflare(DoH) yapmayı deneyebilirsin.

**Comment by quyirah** [comment]
Reqrypt'i açınca hiçbir siteyi açamıyorum ve düne kadar hiç sorun olmadan çalışıyordu 1 seneden beri kullanıyorum. Simple DnsCrypt'i Reqrypt'e başlamadan önce duymuştum ama onu kullanmayı çözemedim. Kablonet'e geçtiğimde VPN dışında sorunumu bir tek Reqrypt çözebilmişti ama o da patladı iki gündür. 
DnsCrypt'i açıp cloudflare işaretliyorum, sonra Reqrypt açıyorum ama yine aynı.

**Comment by Razor221** [comment]
Anladım, şimdi bende reqrypt'i denedim bende de çalışmadı. Sanırım BTK reqrypt gibi programları tamamen engelledi. Ama hala goodbyedpi HTTPS siteler için çalışıyor ama HTTP siteler için çalışmıyor. Kullandığın tarayıcı için "HTTPS Everywhere" eklentisini yükle. Sonra goodbyedpi yükle o zaman yine yasaklı sitelere giriliyor.

**Comment by quyirah** [comment]
Reqrypt'ten önce goodbyedpi kullanıyordum ama Kablonet'te sıkıntılıydı diye hatırlıyorum onu. Paticik diye bir forum var biliyorsundur belki oradan öğrenmiştim Reqrypt'i. Bir oraya sorayım sıkıntı yaşayan var mı diye yoksa da program sahibinden haber bekleyeceğiz...
Bu arada eğer sende de çalışmıyorsa belki de sıkıntı programdan falan kaynaklanıyordur çünkü ben cidden düne kadar sıkıntısız kullanıyordum.

**Comment by Razor221** [comment]
Ben millenicom da yasağın etrafından dolanmayı yine başardım goodbyedpi ile. Ama goodbyedpi HTTPS Everywhere eklentisini chrome'a kurmadan çalışmıyor. Anladığım kadarı ile http filtrelemeyi aşmanın bir yolu yok ama https sitelerdeki filtrelemeyi goodbyedpi ile aşabiliyorsun. HTTPS Everywhere eklentisi bütün siteleri https olarak yönlendiriyor sonra goodbyedpi https filtrelemeyi kaldırıyor ve böylece yasaklı siteler açılıyor. 

Eğer reqrypt ten bir sonuç alamazsan. Yukarda yazdığım yolu deneyebilirsin.

**Comment by quyirah** [comment]
Maalesef GoodbyeDPI kablonette işe yaramıyor sanırım. İlk geçtiğimde de sıkıntı yaşıyordum yine aynı. HTTPS Everywhere de kurdum ama giremiyorum wikipediaya falan.

**Comment by quyirah** [comment]
English sum-up for others;
Reqrypt suddenly stopped working on Turkish ISP's. @Razor221 and I am using different ISP's but we can't connect to any website while using Reqrypt. This may be a problem with Reqrypt's servers or it may be about Turkish ISP's, we don't know yet and we need @basil00's help. Razor221 solved his problem with using GoodbyeDPI program and HTTPS Everywhere addon but my ISP blocked GoodbyeDPI earlier this year...

**Comment by basil00** [comment]
> Is there any way to fix this issue without asking for dedicated IP address?

If increasing the Ghost packet hops does not work then you might be out of luck.  ReQrypt was designed with the assumption that the ISP's processing of packets is stateless so does not track individual connections (unlike CGNAT).  Statelessness was a reasonable assumption back in 2009 when ReQrypt was designed, but these days stateful filtering and CGNAT are more common.

If GoodbyeDPI works then I can recommend using that.  It is even faster than ReQrypt since it does not use servers at all.  The only problem is that GoodbyeDPI is also vulnerable to stateful filtering so may not work forever.

**Comment by quyirah** [comment]
Unfortunately my ISP blocked GoodbyeDPI earlier this year. Also I'm not on CGNAT pool. My IP Address is already static. Is everything okay with ReQrypt servers? Because I was using this program yesterday, without any problem and nothing changed on my side...

**Comment by basil00** [comment]
ReQrypt is down.

So the issue is probably unrelated to your ISP.

There appears to be a problem with the server.  The server is up, but it seems that no packets are being forwarded.  I will need to investigate.

**Comment by quyirah** [comment]
This is good news for me but bad news for you since we have really "hardcore" blockings in Turkey from ISP's. Good luck... :)

**Comment by basil00** [comment]
I've sent a query regarding the server.  It may be down for some time until we figure out the problem.

**Comment by quyirah** [comment]
Looks like servers are working now but it's a bit slower than before.

**Comment by basil00** [comment]
The issue should be fixed for now.  It may go down again as the service provider is apparently moving/reconfiguring things, and the IP address of the server may change.

**Comment by quyirah** [comment]
@basil00 I can't load Wikipedia(Blocked website on Turkey...) with ReQrypt but I can load other blocked websites like Imgur etc. I think there is a specific problem with Wikipedia. 
Chrome error is: DNS_PROBE_FINISHED_NXDOMAIN

**Comment by basil00** [comment]
The `wikipedia.org` domain is probably blocked via DNS poisoning in additional to other methods.  You can try using Google public DNS (`8.8.8.8` or `8.8.4.4`) and enabling the *Hide DNS* mode in ReQrypt.

**Comment by basil00** [comment]
The server migration is complete.  The IP address of the server has changed from `109.248.168.126` to `109.248.207.71`.  The ReQrypt client should still be able to automatically connect via the `taiga.reqrypt.org` domain.

**Comment by gori123** [comment]
sizi nereden yakaladıklarına dair kafayı çalıştırırsanız bu program hala çalışıyor.
