### ISSUE TITLE
How to use

### ISSUE THREAD

**Issue by XakepSDK** [basil00/reqrypt#5]
Reqrypt works only in auto-started browser.
If i start browser manually - it doesn't working. May be i do something wrong?

**Comment by basil00** [comment]
Do you mean that the ReQrypt UI won't load, or that ReQrypt itself stops working?

Either way it should work so perhaps it is a bug.  However, I cannot reproduce yet as it works when I tried it.

**Comment by XakepSDK** [comment]
I fixed it. Just started a script without sudo.
