### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by tazihad** [basil00/reqrypt#50]
I am trying to build this package for Arch linux.
But I am getting build error.
````
collect2: error: ld returned 1 exit status
make[1]: *** [Makefile:74: client] Error 1
make[1]: Leaving directory '/run/media/pulsar/LocalDisk/developments/git-clones/reqrypt/src'
make: *** [Makefile:20: client] Error 2
````

this is the full build log.
[build-log.txt](https://github.com/basil00/reqrypt/files/5569264/build-log.txt)

**Comment by basil00** [comment]
The actual error is:

    /usr/bin/ld: config.o:(.bss+0x0): multiple definition of `config'; client.o:(.bss+0x0): first defined here
    /usr/bin/ld: config.o:(.bss+0x40): multiple definition of `config_lock'; client.o:(.bss+0x40): first defined here

Somehow, those symbols are defined multiple times.
