### ISSUE TITLE
Сервер на Windows

### ISSUE THREAD

**Issue by Eyeborgs** [basil00/reqrypt#51]
Доброго, можно как либо создать свой сервер на Windows? Я уже почитал вашу инструкцию в #38 но я так и не понял как это на Windows развернуть.. 
Потому что когда я устанавливаю ReQrypt он не работает с вашим доменом по умолчанию - возможно провайдер блокирует..

Хотя если не ошибаюсь 2 года назад он работал стабильно у меня на том же провайдере..

**Comment by basil00** [comment]
The server is Linux only and Windows is not supported.
I also tested the default server and it is still working, so it may be blocked at your end.

Сервер работает только с Linux, Windows не поддерживается.
Я также протестировал сервер по умолчанию, и он все еще работает, поэтому он может быть заблокирован на вашей стороне.
