### ISSUE TITLE
Reqrypt is cutting off access to the web

### ISSUE THREAD

**Issue by Bloomfear** [basil00/reqrypt#57]
When I launch Reqrypt, it immediately blocks the connection to any site unless I change it to passive mode but then I can't access the blocked websites. None of the other active modes are working. I am using the standard settings and have never changed anything. I've been using the software for 5 years now, never had problems. Did anything change on the server side? I'm in Turkey.

**Comment by Killogy** [comment]
Yes, it has stopped working.

**Comment by Alexkral** [comment]
It has also stopped working for me, except for some pages like google and youtube.

**Comment by basil00** [comment]
Thanks for the reports.  I am investigating but may take a few days.

**Comment by ValdikSS** [comment]
The server provider has disabled source address spoofing, which is essential for ReQrypt operation. We'll try to find new server, but it will take some time.

**Comment by basil00** [comment]
The ReQrypt service is back online thanks to a new server provided by [Windscribe](https://windscribe.com). We thank Windscribe for their generous support.
