### ISSUE TITLE
I need a server for ip spoofing

### ISSUE THREAD

**Issue by ptpt52** [basil00/reqrypt#7]
I notice that the reqrypt server side must work in a ip-spoofing-server
Actually I am looking for this kind of servers.
I am writing an project for proxy internet access, which works as what you do.
https://github.com/ptpt52/natcap

Could you tell me where I can get this kind of servers( or vps)?

**Comment by basil00** [comment]
Unfortunately it is very hard to find compatible servers these days (it was quite easy in 2009 when reqrypt was first developed).  But if you ask around you may find a provider willing to allow it, as long you explain what it is used for and promise not to abuse it.  See thread here: https://lowendtalk.com/discussion/111813/server-for-legitimate-ip-spoofing-not-ddos-amplification

**Comment by 3245** [comment]
i tested http://hostsale.net/ and it is spoof allowed, you can test them, they has good port...

**Comment by basil00** [comment]
Thanks!  But they seem to only have one VPS plan for $50 per month?  The specs are bit overkill for a `reqryptd` server, but otherwise the unlimited bandwidth is good.

**Comment by 3245** [comment]
they have dedicated servers spoof

**Comment by LetUsFsck** [comment]
VOUCH for hostsale.net! - Really quick spoof boxes for good price.

**Comment by 3245** [comment]
enjoy the quality

**Comment by YourSpoofHost** [comment]
Use https://www.yourspoof.com/ for spoofed server
We are trusted :)

**Comment by basil00** [comment]
This issue is the second most visited page according to github analytics, so it seems there is a market for servers that support spoofing...

I don't mind providers advertising here since some people do want to setup ReQrypt servers, either public or private servers for personal use (if anyone wants to set up a public server then please send me the link or feel free to post it here).  I can't check the quality/suitability of each provider though.

**Comment by YourSpoofHost** [comment]
We changed our organization to https://host-coast.com we offer cheap spoofed servers or bulletproof.
Just give a try ;)

**Comment by LetUsFsck** [comment]
Which organization changed to host-coast? Yourspoof? I am interested in hosts that are able to spoof IP headers, but not for DDoS because that's a crime and I never commit crimes. 

Please send me a message on XMPP at hubr15@riseup.net so we can chat further.

-blackout@stacksma.sh

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by YourSpoofHost** [comment]
> Which organization changed to host-coast? Yourspoof? I am interested in hosts that are able to spoof IP headers, but not for DDoS because that's a crime and I never commit crimes.  Please send me a message on XMPP at hubr15@riseup.net so we can chat further.
> […](#)
> -blackout@stacksma.sh ‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
> On Sunday, April 7, 2019 11:58 AM, YourSpoofHost ***@***.***> wrote: We changed our organization to https://host-coast.com we offer cheap spoofed servers or bulletproof. Just give a try ;) — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or mute the thread.[https://github.com/notifications/beacon/AeroFYUOtmSS1aBfULigdGCT9G3bHOH2ks5vej_wgaJpZM4PMlC0.gif]

I sent to you a message on xmpp

**Comment by HaseebLUMS** [comment]
> We changed our organization to https://host-coast.com we offer cheap spoofed servers or bulletproof.
> Just give a try ;)

it's not working. I want to rent a few cheap servers. @YourSpoofHost  can you please help me

**Comment by YourSpoofHost** [comment]
Hi sir.
https://host-coast.com sir.

35$ first server

Il Mer 8 Mag 2019, 22:31 Muhammad Haseeb <notifications@github.com> ha
scritto:

**Comment by BOLESNI** [comment]
Use justhost.ru, its 2$ vps

**Comment by HeaderHost** [comment]
Headerhost.com | Spoofed VPS-Dedicated servers for cheap price.

**Comment by KieranHewitt-1337** [comment]
https://t.me/rdpac

**Comment by Nacho-Neko** [comment]
@HeaderHost They are scammers, I bought them and they will not reply to me

**Comment by qyservers** [comment]
http://qyservers.xyz/

**Comment by qyservers** [comment]
> I notice that the reqrypt server side must work in a ip-spoofing-server
> Actually I am looking for this kind of servers.
> I am writing an project for proxy internet access, which works as what you do.
> https://github.com/ptpt52/natcap
> 
> Could you tell me where I can get this kind of servers( or vps)?

http://qyservers.xyz/

**Comment by scramblr** [comment]
> > I notice that the reqrypt server side must work in a ip-spoofing-server
> > Actually I am looking for this kind of servers.
> > I am writing an project for proxy internet access, which works as what you do.
> > https://github.com/ptpt52/natcap
> > Could you tell me where I can get this kind of servers( or vps)?
> 
> http://qyservers.xyz/

lmfao nice prices. you can buy spoofing servers for $1/month if you look hard enough, but feel free to spend your money with these scammers.

**Comment by qyservers** [comment]
Spoofing server for $ 1 in 2020?

**Comment by BOLESNI** [comment]
@qyservers justhost.ru :) If you use it for a ddos your network will be limited, but if you use it for something like this it will work perfectly.

**Comment by GeorgeHarter** [comment]
Just use spackhost.com
They have spoofed and bulletproof server and they are trusted (he is my friend selling those servers privately from like 2015)

**Comment by blazorin** [comment]
Spackhost just resells non-spoofed from tomahost.
I tried **spoofed.nitroservers.io** and worked for me without issues. Very fast support and installation.
Hope this helps anyone.

**Comment by GeorgeHarter** [comment]
Oh jesus, another shit hosting with shit scamming domain, guys absolutely don’t trust spoofed.nistroservers.io 1) Scamming website 2) If not scamming is a shit reseller. Spackhost.com is trusted with 1000+ active servers and 6 nodes online status.spackhost.com the guy above me is telling only bullshit 1) he never tried spackhost 2) we have own hardware colocated in romania, ukraina and russia 3) we have own router, we decide if spoofed is enabled or not 4) 24/7 support 5) Vouch from over 100+ people on discord


don’t tell bullshit your hosting spoofed.nitroservers.io is another SCAMMING host!! SCAMMER


Use spackhost.com as we are trusted.

**Comment by GeorgeHarter** [comment]
Also, spackhost is instant installation wtf are u saying mf 😂

**Comment by blazorin** [comment]
bro just  explain this
![image](https://user-images.githubusercontent.com/32218025/80829756-06bdd880-8be8-11ea-9ccb-ce71c3ada5d5.png)
https://www.linkedin.com/company/thc-projects-srl
THC Servers.

**Comment by GeorgeHarter** [comment]
Ahaha, a differenza tua ho contratti con datacenters, THCProjects is not spoofing, we have colocation in his datacenter but we have our router, hardware and traffic, they installed his ASN in our router. Now? Scammer reseller?

**Comment by HaseebLUMS** [comment]
Why am I included in your emails? Please stop it.

**Comment by hurry989** [comment]
I need a scan server

**Comment by GeorgeHarter** [comment]
Scan servers: https://spackhost.com/bulletproofvps

**Comment by hurry989** [comment]
> 扫描服务器：[https](https://spackhost.com/bulletproofvps) : [//spackhost.com/bulletproofvps](https://spackhost.com/bulletproofvps)

15.99$？

**Comment by BOLESNI** [comment]
> I need a scan server

Dont use spackhost, its a scam.

**Comment by hurry989** [comment]
> > 我需要扫描服务器
> 
> 不要使用spackhost，这是一个骗局。

So you have a better scanning server

**Comment by GeorgeHarter** [comment]
Lol, spackhost is not a scam. They have own datacenter. Bolesni u kid turk lol

**Comment by GeorgeHarter** [comment]
Use spackhost.

**Comment by hurry989** [comment]
So I need to buy that server. How much is it

**Comment by BOLESNI** [comment]
> Lol, spackhost is not a scam. They have own datacenter. Bolesni u kid turk lol
I'am not a Turk. Stop ripping people.

**Comment by mufeng666** [comment]
**STRESSERHOME.COM is best web stresser or ddos ip booter of 2020, with Layer 3, Layer 4 and Layer 7 ddos methods**

**Comment by mufeng666** [comment]
STRESSERHOME.COM is best web stresser or ddos ip booter of 2020, with Layer 3, Layer 4 and Layer 7 ddos methods

**Comment by blazorin** [comment]
> STRESSERHOME.COM is best web stresser or ddos ip booter of 2020, with Layer 3, Layer 4 and Layer 7 ddos methods

fun fact it's synstresser design + booter.world 2016 leaked source lmao

**Comment by blazorin** [comment]
[beta.stress.pw](https://beta.stress.pw) it's much better lol
