### ISSUE TITLE
Increase default ghost packet hops

### ISSUE THREAD

**Issue by ValdikSS** [basil00/reqrypt#8]
ReQrypt won't work out of the box behind several NATs or Carrier-Grade NAT, as default ghost packet hops number is set to 2. I propose to increase default value up to 4. In my opinion, this is sane number to punch NAT but not to route packet to DPI or similar filtering system.

**Comment by basil00** [comment]
I think 2 was chosen since it was enough for a typical PC->modem/router setup.  Ideally it should be number of hops to the NAT+1, and less than the number of hops to the filtering system.

I am not sure what the best number is.  Maybe 4 is a better default.  But what about 3?

**Comment by ValdikSS** [comment]
3 should be fine too I suppose. Not sure if it's acceptable for CGN, but for typical home use it should be sufficient.
