### ISSUE TITLE
32 bit Windows version

### ISSUE THREAD

**Issue by ValdikSS** [basil00/reqrypt#9]
Some people on Russian forums complain that there's no 32 bit build of ReQrypt. They probably use laptops with low amount of soldered (non-replaceable) RAM.
Please make 32 bit build if it's not too hard.

**Comment by basil00** [comment]
I have a build, but completely untested.  Do you still want it?

Note that the Windows build seems to be problematic.  When I compile with recent versions of MinGW it seems to generate a broken executable (for 64 bit), so I had to build the latest release with an older MinGW.

**Comment by ValdikSS** [comment]
Yes, I'll publish it on nnm-club.
Please file a bug to MinGW developers too.

**Comment by basil00** [comment]
I added the 32bit versions [here](https://reqrypt.org/download/).  Note they are completely untested.

As for MinGW, it is not clear if this is a bug in MinGW or ReQrypt.  I think more likely it is ReQrypt, i.e., some undefined behavior which is compiled differently depending on the compiler version.
